include:
  - remote: 'https://gitlab.com/pod_security/shared-ci/-/raw/main/security.yml'
# Define cache settings
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

# Define default image for all jobs
image: 'registry.gitlab.com/shardus/dev-container:latest_node18'

# Define stages for the pipeline
stages:
  - prepare
  - build_and_lint_and_check
  - appsec

# Prepare job: Install Node.js dependencies
prepare-job:
  stage: prepare
  script:
    - node -v
    - apt-get update
    - npm ci  #install Node.js dependencies

# Common configuration for jobs
.common-job-template: &common-job-template
  before_script:
    - node -v

# Lint job: Run ESLint for code linting
.lint-job:
  <<: *common-job-template
  stage: build_and_lint_and_check
  needs: ['prepare-job']
  script:
    - echo "Running ESLint..."
    - npm run lint
    - echo "Running ESLint complete."

# Build job: Build the code
build-job:
  <<: *common-job-template
  stage: build_and_lint_and_check
  needs: ['prepare-job']  
  script:
    - echo "Compiling the code..."
    - npm run prepare
    - echo "Compile complete."
  artifacts:
    paths:
      - build/

# Check stage: Perform code checks and tests
depcheck-job:
  stage: build_and_lint_and_check
  needs: ['prepare-job']
  variables:
    NODE_ENV: test

  script:
    - npm run depcheck # analyze dependencies and identify unused or outdated packages.
    - npm run test
