export enum TypeIdentifierEnum {
  cApoptosisProposalReq = 1,
  cApoptosisProposalResp,
  cWrappedReq,
  cWrappedResp,
  cWrappedData,
  cBroadcastStateReq,
  cSendCachedAppDataReq,
  cCachedAppData,
  cGetAccountDataWithQueueHintsReq,
  cGetAccountDataWithQueueHintsResp,
  cWrappedDataFromQueue,
  cGetAccountQueueCountReq,
  cGetAccountQueueCountResp,
  cGetAccountDataByListReq,
  cGetAccountDataByListResp,
  cWrappedDataSyncSerialized,
  cGetAccountData3Req,
  cGetAccountData3Resp,
  cGetAccountData3Array,
  cWrappedGAD3Array,
  cWrappedGAD3,
  cGetTxTimestamp,
}
