import { StrictLogsConfiguration } from '../shardus/shardus-types'

const LOGS_CONFIG: StrictLogsConfiguration = {
  saveConsoleOutput: true,
  dir: 'logs',
  files: { main: '', fatal: '', net: '', app: '', seq: '' },
  options: {
    appenders: {
      out: { type: 'console', maxLogSize: 10000000, backups: 10 },
      seq: {
        type: 'dateFileWithSize',
        pattern: 'yyyy-MM-dd-HH-mm-ss',
        keepFileExt: true,
        maxLogSize: 10485760,
        backups: 10,
        numBackups: 10,
        compress: false,
        alwaysIncludePattern: false,
      },
      main: {
        type: 'dateFileWithSize',
        pattern: 'yyyy-MM-dd-HH-mm-ss',
        keepFileExt: true,
        maxLogSize: 10485760,
        backups: 10,
        numBackups: 10,
        compress: false,
        alwaysIncludePattern: false,
      },
      app: {
        type: 'dateFileWithSize',
        pattern: 'yyyy-MM-dd-HH-mm-ss',
        keepFileExt: true,
        maxLogSize: 10485760,
        backups: 10,
        numBackups: 10,
        compress: false,
        alwaysIncludePattern: false,
      },
      p2p: {
        type: 'dateFileWithSize',
        pattern: 'yyyy-MM-dd-HH-mm-ss',
        keepFileExt: true,
        maxLogSize: 10485760,
        backups: 10,
        numBackups: 10,
        compress: false,
        alwaysIncludePattern: false,
      },
      snapshot: {
        type: 'dateFileWithSize',
        pattern: 'yyyy-MM-dd-HH-mm-ss',
        keepFileExt: true,
        maxLogSize: 10485760,
        backups: 10,
        numBackups: 10,
        compress: false,
        alwaysIncludePattern: false,
      },
      cycle: {
        type: 'dateFileWithSize',
        pattern: 'yyyy-MM-dd-HH-mm-ss',
        keepFileExt: true,
        maxLogSize: 10485760,
        backups: 10,
        numBackups: 10,
        compress: false,
        alwaysIncludePattern: false,
      },
      fatal: {
        type: 'dateFileWithSize',
        pattern: 'yyyy-MM-dd-HH-mm-ss',
        keepFileExt: true,
        maxLogSize: 10485760,
        backups: 10,
        numBackups: 10,
        compress: false,
        alwaysIncludePattern: false,
      },
      exit: {
        type: 'dateFileWithSize',
        pattern: 'yyyy-MM-dd-HH-mm-ss',
        keepFileExt: true,
        maxLogSize: 10485760,
        backups: 10,
        numBackups: 10,
        compress: false,
        alwaysIncludePattern: false,
      },
      errorFile: {
        type: 'dateFileWithSize',
        pattern: 'yyyy-MM-dd-HH-mm-ss',
        keepFileExt: true,
        maxLogSize: 10485760,
        backups: 10,
        numBackups: 10,
        compress: false,
        alwaysIncludePattern: false,
      },
      errors: { type: 'logLevelFilter', level: 'ERROR', appender: 'errorFile' },
      net: {
        type: 'dateFileWithSize',
        pattern: 'yyyy-MM-dd-HH-mm-ss',
        keepFileExt: true,
        maxLogSize: 10485760,
        backups: 10,
        numBackups: 10,
        compress: false,
        alwaysIncludePattern: false,
      },
      playback: {
        type: 'dateFileWithSize',
        pattern: 'yyyy-MM-dd-HH-mm-ss',
        keepFileExt: true,
        maxLogSize: 10485760,
        backups: 10,
        numBackups: 10,
        compress: false,
        alwaysIncludePattern: false,
      },
      shardDump: {
        type: 'dateFileWithSize',
        pattern: 'yyyy-MM-dd-HH-mm-ss',
        keepFileExt: true,
        maxLogSize: 10485760,
        backups: 10,
        numBackups: 10,
        compress: false,
        alwaysIncludePattern: false,
      },
      statsDump: {
        type: 'dateFileWithSize',
        pattern: 'yyyy-MM-dd-HH-mm-ss',
        keepFileExt: true,
        maxLogSize: 10485760,
        backups: 10,
        numBackups: 10,
        compress: false,
        alwaysIncludePattern: false,
      },
    },
    categories: {
      default: { appenders: ['out'], level: 'trace' },
      app: { appenders: ['app', 'errors'], level: 'trace' },
      main: { appenders: ['main', 'errors'], level: 'trace' },
      seq: { appenders: ['seq'], level: 'trace' },
      p2p: { appenders: ['p2p'], level: 'trace' },
      snapshot: { appenders: ['snapshot'], level: 'trace' },
      cycle: { appenders: ['cycle'], level: 'trace' },
      fatal: { appenders: ['fatal'], level: 'fatal' },
      exit: { appenders: ['exit'], level: 'fatal' },
      net: { appenders: ['net'], level: 'trace' },
      playback: { appenders: ['playback'], level: 'trace' },
      shardDump: { appenders: ['shardDump'], level: 'trace' },
      statsDump: { appenders: ['statsDump'], level: 'trace' },
    },
  },
}

export default LOGS_CONFIG
